### ISSUE TITLE
Nested Functions Throw Syntax Error

### ISSUE THREAD

**Issue by matthewfriedrichs** [FrankBuss/Formula#1]
I recently found that nesting functions can cause syntax errors in code that should compile just fine. The following four examples should all return the same result, but the third one will throw a syntax error and not compile.

pow(2,2) = 4
pow(2,abs(-2)) = 4
pow(abs(2),abs(-2)) = syntax error
pow(2,abs(-2*pow(1,abs(1-2)))) = 4

I have found that nesting a function in the first argument of many functions will cause a syntax error. The first occurrence of this was when I was taking the maximum value of floored modulation sources.

max(floor(x), y) = syntax error
max(x,floor(y)) = runs as expected
max(floor(x), floor(y)) = syntax error

I have compiled the latest master branch on Windows 10. It is currently unmodified to confirm that this bug is not caused from my edits to the code.

If for some reason the above equations run just fine on Linux or Mac, please let me know. I love this tool since it opens up coding in rack to those who do no wish to set up a full development environment.

**Comment by FrankBuss** [comment]
Thanks, it is fixed now. BTW, instead of pow, you could write abs(2)^abs(-2). I guess the pow operator is kind of redundant, but some people might prefer it over the ^ operator. I also added a printf for easier debugging other bugs, and there was a memory leak.

**Comment by FrankBuss** [comment]
After looking again at it, I think there was no memory leak, but it is clearer now. Maybe a good idea to encapsulate the raw pointers all with smart pointers.
